svn_path: C:\\Program Files\\Subversion\\bin\\svn.exe
script_class_folder_path: F:\\automationTest\\Florida\\bin\\
screenshot_path: C:/QA Automation/Membership/trunk/framework/screen_shots/

testng_jar_path: C:\\testng-5.14.jar
testplus_listener_path: C:\\TestPlusListener-0.0.1-SNAPSHOT.jar
dom4j_path: C:\\dom4j-2.0.0-ALPHA-2.jar
httpclient_path: C:\\httpclient-4.1.2.jar
httpcore_path: C:\\httpcore-4.1.2.jar
selenium_server_path: C:\\selenium-server.jar
