--- !ruby/object:ClientConfig
identity: test_slave#1
ip_address: 0.0.0.0
machine_info: !ruby/object:MachineInfo
  name: Tyrael Tong's MBP
  os: Mac OS X
  version: 10.6
  browsers_info:
  - !ruby/object:BrowserInfo
    name: Safari
    version: 6.0.1
capabilities:
- !ruby/object:CapabilityInfo
  name: qtp
  version: 10.0
  status: busy
- !ruby/object:CapabilityInfo
  name: soapui
  version: 6.0
  status: busy