--- !ruby/object:ClientConfig
identity: machineName#IPAddress
ip_address: 0.0.0.0
market: camps
machine_info: !ruby/object:MachineInfo
  name: Tyrael Tong's MBP
  os: Mac OS X
  version: 10.6
  browsers_info:
  - !ruby/object:BrowserInfo
    name: Safari
    version: 6.0.1
    allowed: true
capabilities:
- !ruby/object:CapabilityInfo
  name: qtp
  version: 10.0
  status: free
  allowed: false
